### ISSUE TITLE
htmlentities

### ISSUE THREAD

**Issue by foxmask** [sametmax/Bat-belt#4]
with PHP with have [htmlentities](http://php.net/manual/en/function.htmlentities.php) to convert char to html entity / [html_entiy_decode](http://php.net/manual/en/function.html-entity-decode.php) to revert this behavior.
Would you like to add this to bat-belt ?
You can have a look at https://github.com/foxmask/django-th/blob/master/django_th/html_entities.py I made yesterday to deal with it.
I could make a PR if you want ; otherswise close this ticket :)

**Comment by sametmax** [comment]
I think Python got this already : http://stackoverflow.com/questions/2087370/decode-html-entities-in-python-string and https://docs.python.org/3/library/html.entities.html

**Comment by foxmask** [comment]
I didnt see it for python 3 .
So forget it ;)
